// site/pages/index.vue
<template>
  <main
    class="my-24 flex flex-1 flex-col items-center justify-center text-center font-['JetBrains_Mono']"
  >
    <div class="space-y-24">
      <div class="text-[10vw]">
        <HomeIntro />
      </div>
    </div>
  </main>
</template>

<script setup>
useSeoMeta({
  title: "xithrius.cloud",
});
</script>

// site_factorio/pages/index.tsx
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>factorio.xithrius.cloud</title>
        <link rel="icon" href="/logo.png" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center py-2"></div>
    </>
  );
};

export default Home;
