// site/pages/index.vue
<template>
  <main
    class="my-24 flex flex-1 flex-col items-center justify-center text-center font-['JetBrains_Mono']"
  >
    <div class="space-y-24">
      <div class="text-[10vw]">
        <HomeIntro />
      </div>
    </div>
  </main>
</template>

<script setup>
useSeoMeta({
  title: "xithrius.cloud",
});
</script>

// site_projects/pages/index.tsx
import type { NextPage } from "next";
import Head from "next/head";

export default function Home({}: NextPage) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2">
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <h1 className="text-6xl font-bold">
          Welcome to{" "}
          <a className="text-blue-600" href="https://nextjs.org">
            Next.js!
          </a>
        </h1>
      </main>
    </div>
  );
};
